import json
from datetime import datetime

INPUT_FILE = "cross_scenario_analytics.json"
OUTPUT_FILE = "scenario_drilldown_report.md"


def _as_list(value):
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def build_report(data):
    lines = []
    lines.append(f"# Scenario Drilldown Report - {datetime.now().strftime('%Y-%m-%d')}\n")
    lines.append("## Portfolio Risk Summary\n")

    risk_buckets = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Unknown": 0}
    for _, payload in data.items():
        risks = _as_list(payload.get("risk_levels", []))
        if not risks:
            risk_buckets["Unknown"] += 1
            continue
        for risk in risks:
            if risk in risk_buckets:
                risk_buckets[risk] += 1
            else:
                risk_buckets["Unknown"] += 1

    lines.append("| Risk Level | Scenario Count |\n")
    lines.append("|------------|----------------|\n")
    for k in ["Critical", "High", "Medium", "Low", "Unknown"]:
        lines.append(f"| {k} | {risk_buckets[k]} |\n")

    lines.append("\n## Scenario Drilldown\n")
    for scenario in sorted(data.keys()):
        payload = data[scenario]
        signals = _as_list(payload.get("signals", []))
        actions = _as_list(payload.get("actions", []))
        risks = _as_list(payload.get("risk_levels", []))
        classifications = _as_list(payload.get("classifications", []))

        lines.append(f"### {scenario}\n")
        lines.append(f"- Classification: {', '.join(classifications) if classifications else 'N/A'}\n")
        lines.append(f"- Risk: {', '.join(risks) if risks else 'Unknown'}\n")
        lines.append(f"- Signal Count: {len(signals)}\n")
        lines.append(f"- Action Count: {len(actions)}\n")
        lines.append(f"- Top Signals: {', '.join(signals[:3]) if signals else 'None'}\n")
        lines.append(f"- Recommended Actions: {', '.join(actions[:3]) if actions else 'None'}\n\n")

    lines.append("---\nGenerated by scenario_drilldown_report.py\n")
    return lines


def main():
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    lines = build_report(data)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.writelines(lines)

    print(f"Drilldown report written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
